# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-12 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TickData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('seconds_to_poll', models.FloatField()),
                ('tick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutu.Tick')),
            ],
        ),
    ]
